name: Nightly Snapshot

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  tag:
    name: Tag
    runs-on: macos-latest
    steps:
      - name: Checkout branch "develop"
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Tag snapshot
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: ${{ steps.date.outputs.date }}
