name: Nightly Snapshot

on:
  schedule:
  - cron: "0 0 * * *"
  
jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get New Tag
        id:   newTag
        run:  echo "::set-output name=newTag::$(swift $GITHUB_WORKSPACE/.github/workflows/nightly\ snapshot.swift)"
          
      - name: Tag Snapshot
        if:   steps.newTag.outputs.newTag != null
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag:        ${{ steps.newTag.outputs.newTag }}
