name: Nightly Snapshot

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    name: Release
    runs-on: macos-latest
    steps:
      - name: Checkout branch "develop"
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name: Release snapshot
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 'nightly snapshot'
          draft: false
          prerelease: false
