name: Workflow Debug

on: push

jobs:
  debug:
    name: Debug
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - run: git rev-parse --abbrev-ref HEAD
      - run: git rev-parse HEAD
      - run: git rev-parse --abbrev-ref --tags
